
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wiring_app_development
test:
  <<: *default
  database: wiring_app_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
